package com.prep.backend.service;

import java.util.List;

import org.springframework.stereotype.Service;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.prep.backend.dto.PracticeQuestionResponse;

@Service
public class PracticeQuestionService {

  private final GeminiService geminiService;
private final ObjectMapper objectMapper = new ObjectMapper();

public PracticeQuestionService(GeminiService geminiService) {
    this.geminiService = geminiService;
}

    public List<PracticeQuestionResponse> generateQuestions(
            String section,
            String difficulty
    ) {

        String prompt = """
                Generate exactly 30 multiple-choice practice questions for an aptitude
                and placement preparation test.

                Section: %s
                Difficulty: %s

                Requirements:
                - Generate exactly 30 questions.
                - Every question must belong to the selected section.
                - Follow the selected difficulty level.
                - Each question must have exactly 4 options.
                - Only one option must be correct.
                - The answer must be represented as a zero-based index:
                  0 = first option
                  1 = second option
                  2 = third option
                  3 = fourth option.
                - Include a short explanation for every answer.
                - Do not include duplicate questions.
                - Do not include topics outside the selected section.
                - Questions should be suitable for college placement preparation.
                - Return ONLY valid JSON.
                - Do not use markdown.
                - Do not add ```json or ``` around the response.

                Return exactly this JSON structure:

                [
                  {
                    "question": "Question text",
                    "options": [
                      "Option A",
                      "Option B",
                      "Option C",
                      "Option D"
                    ],
                    "answer": 0,
                    "explanation": "Short explanation"
                  }
                ]
                """.formatted(section, difficulty);

String response = geminiService.generatePracticeQuestions(prompt);
        try {
            return objectMapper.readValue(
                    response,
                    new TypeReference<List<PracticeQuestionResponse>>() {}
            );
        } catch (Exception e) {
            throw new RuntimeException(
                    "Failed to parse practice questions generated by Gemini",
                    e
            );
        }
    }
}